[project]
name = "check-splice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ljw", email = "ljw2017@sjtu.edu.cn" }
]
requires-python = "==3.13.*"
dependencies = [
    "bioframe>=0.8.0",
    "coolbox>=0.4.0",
    "ipykernel>=7.3.0",
    "pandas[feather]>=3.0.5",
    "plotnine>=0.15.7",
    "py2bit>=1.0.1",
    "pybigwig>=0.3.25",
    "pypdf>=6.16.1",
    "pysam>=0.24.0",
    "sh>=2.4.0",
]

[project.scripts]
check-splice = "check_splice:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
