[project]
name = "check-splice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ljw", email = "ljw2017@sjtu.edu.cn" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "plotnine>=0.15.7",
    "pysam>=0.24.0",
]

[project.scripts]
check-splice = "check_splice:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
